-- 관심고객 등록 및 추적을 위한 테이블 (이름: 거제 센트레빌 이대진)
CREATE TABLE IF NOT EXISTS "거제 센트레빌 이대진" (
  id bigint generated by default as identity primary key,
  name text,
  phone text,
  agreed_to_privacy boolean,
  source text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS (Row Level Security) 활성화 및 누구나 데이터 추가(Insert)할 수 있도록 허용
ALTER TABLE "거제 센트레빌 이대진" ENABLE ROW LEVEL SECURITY;

-- 기존 정책이 있다면 삭제 (오류 방지)
DROP POLICY IF EXISTS "Allow public inserts" ON "거제 센트레빌 이대진";
DROP POLICY IF EXISTS "Allow anon inserts" ON "거제 센트레빌 이대진";

CREATE POLICY "Allow anon inserts" ON "거제 센트레빌 이대진"
  FOR INSERT
  TO public
  WITH CHECK (true);

-- 전화 연결 버튼 등 단순 클릭 트래킹이 필요할 경우를 대비한 추가 테이블 (선택 사항)
CREATE TABLE IF NOT EXISTS "거제 센트레빌 전화클릭" (
  id bigint generated by default as identity primary key,
  click_type text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

ALTER TABLE "거제 센트레빌 전화클릭" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public inserts telefon" ON "거제 센트레빌 전화클릭";
DROP POLICY IF EXISTS "Allow anon inserts telefon" ON "거제 센트레빌 전화클릭";

CREATE POLICY "Allow anon inserts telefon" ON "거제 센트레빌 전화클릭"
  FOR INSERT
  TO public
  WITH CHECK (true);
